Repository openshift/oauth-server, pull requests merged in 2019-12, with the labels that each got.

#25 Add mfojtik, sttts, stlaz to approvers
  OWNERS
Labels: approved, lgtm, size/XS

#22 Fix smallish typo in the test
  pkg/oauthserver/oauth_apiserver_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#20 Fix pseudoversion of osincli dependency for go1.13
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/XS

#26 Bug 1671604: Add bootstrap idp only when bootstrap user is enabled
  go.mod
  go.sum
  pkg/oauthserver/oauth_apiserver.go
  vendor/github.com/certifi/gocertifi/gen.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/Makefile
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/build.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/test-unit.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/verify-update.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/bindata.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/rpm.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/yq.mk
  vendor/github.com/openshift/library-go/pkg/authentication/bootstrapauthenticator/bootstrap.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/client_metrics.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/workqueue_metrics.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL
