Repository openshift/oauth-server, pull requests merged in 2020-04, with the labels that each got.

#36 Pick up PatternFly bug fix [1] for login templates
  pkg/server/errorpage/templates.go
  pkg/server/login/templates.go
  pkg/server/selectprovider/templates.go
Labels: approved, lgtm

#37 Bug 1822122: Add back some missing metrics
  go.mod
  go.sum
  pkg/prometheus/metrics.go
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/cryptobyte/string.go
  vendor/golang.org/x/crypto/poly1305/bits_compat.go
  vendor/golang.org/x/crypto/poly1305/bits_go1.13.go
  vendor/golang.org/x/crypto/poly1305/poly1305.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/poly1305/sum_arm.go
  vendor/golang.org/x/crypto/poly1305/sum_arm.s
  vendor/golang.org/x/crypto/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/poly1305/sum_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/k8s.io/client-go/util/connrotation/connrotation.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm

#39 Add component to OWNERS
  OWNERS
Labels: approved, lgtm

#40 Bug 1823772: 4.4: Add back some missing metrics
  go.mod
  go.sum
  pkg/prometheus/metrics.go
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/cryptobyte/string.go
  vendor/golang.org/x/crypto/poly1305/bits_compat.go
  vendor/golang.org/x/crypto/poly1305/bits_go1.13.go
  vendor/golang.org/x/crypto/poly1305/poly1305.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/poly1305/sum_arm.go
  vendor/golang.org/x/crypto/poly1305/sum_arm.s
  vendor/golang.org/x/crypto/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/poly1305/sum_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/k8s.io/client-go/util/connrotation/connrotation.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm
