Repository openshift/oauth-server, pull requests merged in 2021-02, with the labels that each got.

#66 Bug 1905991: Detecting broken connections to the Kube API takes up to 15 minutes
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/config/client/client_config.go
  vendor/github.com/openshift/library-go/pkg/network/dialer.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go
  vendor/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader_controller.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/timeout.go
  vendor/k8s.io/apiserver/pkg/server/filters/wrap.go
  vendor/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication_dynamic_request_header.go
  vendor/k8s.io/apiserver/pkg/server/options/authorization.go
  vendor/k8s.io/apiserver/pkg/server/patch.go
  vendor/k8s.io/apiserver/pkg/server/routes/openapi.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#65 Bug 1894918: Panic output due to timeouts in oauth-apiserver
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go
  vendor/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader_controller.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/timeout.go
  vendor/k8s.io/apiserver/pkg/server/filters/wrap.go
  vendor/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication_dynamic_request_header.go
  vendor/k8s.io/apiserver/pkg/server/options/authorization.go
  vendor/k8s.io/apiserver/pkg/server/patch.go
  vendor/k8s.io/apiserver/pkg/server/routes/openapi.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#69 Bug 1892642: metrics: move unlabeled metrics to Counters, initialize all
  pkg/prometheus/metrics.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
