Repository openshift/oauth-server, pull requests merged in 2022-05, with the labels that each got.

#106 AUTH-100: Add request header authn auditing
  pkg/audit/annotation.go
  pkg/audit/authreq.go
  pkg/audit/authreq_test.go
  pkg/authenticator/request/headerrequest/requestheader.go
  pkg/authenticator/request/headerrequest/requestheader_test.go
  pkg/oauth/handlers/authenticator.go
  pkg/oauth/handlers/authenticator_test.go
  pkg/oauthserver/auth.go
Labels: approved, lgtm

#103 Bug 2086465: External OAuth: create audit logs for auth events
  pkg/api/errors.go
  pkg/oauth/external/github/github.go
  pkg/oauth/external/github/github_test.go
  pkg/oauth/external/gitlab/gitlab_oauth.go
  pkg/oauth/external/handler.go
  pkg/oauth/external/handler_test.go
  pkg/oauth/external/interfaces.go
  pkg/oauth/external/openid/openid.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#108 Bug 2086505: Updating oauth-server images to be consistent with ART
  .ci-operator.yaml
  go.mod
  go.sum
  images/Dockerfile.rhel
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low
